name: "Deveel Filters CI/CD"

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  build:
    name: "Build (.NET ${{ matrix.dotnet-version }})"
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x', '8.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: "Setup .NET Core"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: "Restore"
        run: dotnet restore

      - name: "Build"
        run: dotnet build -c Release --no-restore

      - name: "Test"
        run: dotnet test -c Release --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*.XUnit]*"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: "Publish Packages"
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish-packages.yml

  clean:
    name: Cleaning Old Packages
    needs: publish
    uses: ./.github/workflows/clean-packages.yml