name: "Deveel Filters PR Build"

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build (.NET ${{ matrix.dotnet-version }})"
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x', '8.0.x']

    steps:
      - uses: actions/checkout@v4
  
      - name: "Setup .NET ${{ matrix.dotnet-version }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: "Restore"
        run: dotnet restore

      - name: "Build"
        run: dotnet build -c Release --no-restore

      - name: "Test"
        run: dotnet test -c Release --no-restore --no-build --verbosity normal