name: "Deveel Filters PR Build"

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build (.NET ${{ matrix.dotnet-version }})"
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - dotnet-version: '6.0.x'
            dotnet-moniker: 'net6.0'
          - dotnet-version: '7.0.x'
            dotnet-moniker: 'net7.0'
          - dotnet-version: '8.0.x'
            dotnet-moniker: 'net8.0'

    steps:
      - uses: actions/checkout@v4
  
      - name: "Setup .NET ${{ matrix.dotnet-version }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: "Restore"
        run: dotnet restore -p:TargetFramework=${{ matrix.dotnet-moniker }}

      - name: "Build"
        run: dotnet build -c Release --no-restore --framework ${{ matrix.dotnet-moniker }}

      - name: "Test"
        run: dotnet test -c Release --no-restore --no-build --verbosity normal --framework ${{ matrix.dotnet-moniker }}