name: "Publish Packages"

on:
  workflow_call:
    inputs:
      nuget:
        description: 'Whether to publish to NuGet.org'
        required: false
        type: boolean
        default: false

jobs:
  publish:
    name: "Publish (.NET ${{ matrix.dotnet-version }})"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Setup .NET ${{ matrix.dotnet-version }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: "Pack"
        run: dotnet pack -c Release --verbosity normal --include-symbols --include-source --version-suffix $GITHUB_RUN_ID --output ./nuget

      - name: "Push Packages to GitHub Nuget"
        run: dotnet nuget push ./nuget/*.nupkg --source https://nuget.pkg.github.com/deveel --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: "Push Packages to NuGet.org"
        if: ${{ inputs.nuget == true }}
        run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate