name: "Release"

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    name: "Builds (.NET ${{ matrix.dotnet-version }})"
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dotnet-version: '6.0.x'
            framework-moniker: 'net6.0'
          - dotnet-version: '7.0.x'
            framework-moniker: 'net7.0'
          - dotnet-version: '8.0.x'
            framework-moniker: 'net8.0'

    steps:
      - uses: actions/checkout@v4

      - name: "Extract version from tag"
        id: extract_version
        run: |
          # Remove 'v' prefix from tag and extract version
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: "Setup .NET ${{ matrix.dotnet-version }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: "Restore"
        run: dotnet restore

      - name: "Build"
        run: dotnet build -c Release --no-restore --framework ${{ matrix.framework-moniker }}

      - name: "Test"
        run: dotnet test -c Release --no-restore --no-build --framework ${{ matrix.framework-moniker }} --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*.XUnit]*"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: "Publish Packages"
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: "Setup .NET .NET 8.0"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: "Pack"
        run: dotnet pack -c Release --verbosity normal --include-symbols --include-source --version-suffix $GITHUB_RUN_ID --output ./nuget
      
      - name: "Push Packages to GitHub Nuget"
        run: dotnet nuget push ./nuget/*.nupkg --source https://nuget.pkg.github.com/deveel --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Publish to NuGet
        run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

  clean:
    name: "Cleaning Old Packages"
    needs: publish
    uses: ./.github/workflows/publish-packages.yml

  create-release:
    name: "Create GitHub Release"
    needs: publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: "Extract version from tag"
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: "Create Release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false